### ISSUE TITLE
kcr shell --session ends with exception on mac

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/kakoune.cr#12]
Invoking `kcr shell --session test` on mac raises exception:
```
Create the session: test
Unhandled exception: Error executing process: 'setsid': No such file or directory (File::NotFoundError)
  from /usr/local/Cellar/crystal/1.0.0/src/crystal/system/unix/process.cr:225:34 in 'raise_exception_from_errno'
  from /usr/local/Cellar/crystal/1.0.0/src/crystal/system/unix/process.cr:156:9 in 'spawn'
  from /usr/local/Cellar/crystal/1.0.0/src/process.cr:230:21 in 'create'
  from .config/kak/plugins/github.com/alexherbo2/kakoune.cr/src/cli.cr:364:9 in 'start'
  from .config/kak/plugins/github.com/alexherbo2/kakoune.cr/src/cli.cr:597:1 in '__crystal_main'
  from /usr/local/Cellar/crystal/1.0.0/src/crystal/main.cr:110:5 in 'main'
```

**Comment by alexherbo2** [comment]
It looks macOS doesn’t have `setsid`.

**Comment by alexherbo2** [comment]
Can you try to create a session named `test` with the following code:

``` sh
crystal eval <<EOF
  lib C
    fun setsid
  end

  Process.fork do
    C.setsid
    Process.run("kak", { "-s", "test", "-d" })
  end
EOF
```

The server should survive closing the terminal.

See [C bindings] for reference.

[C bindings]: https://crystal-lang.org/reference/syntax_and_semantics/c_bindings/

**Comment by vbauerster** [comment]
> It looks macOS doesn’t have `setsid`.

You're right, there is no such executable in mac.

`kak -l` shows nothing, after invoking the snippet with C bindings.

**Comment by alexherbo2** [comment]
According to the manual, the signature for `setsid()` is:

```
pid_t setsid(void);
```

Does it work better if you update with:

``` crystal
lib C
  fun setsid : Int32
end
```

**Comment by alexherbo2** [comment]
Apparently, we should double fork to orphan the server, like in [`fork_server_to_background()`].

[`fork_server_to_background()`]: https://github.com/mawww/kakoune/blob/master/src/main.cc#:~:text=fork_server_to_background

``` crystal
lib C
  fun setsid : Int32
end

class Process
  def self.setsid(command, arguments)
    fork do
      C.setsid

      # Double fork to orphan the server.
      fork do
        new(command, arguments)
      end
    end
  end
end

Process.setsid("kak", { "-s", "test", "-d" })
```

**Comment by vbauerster** [comment]
Thank you! I confirm that's been fixed.
