### ISSUE TITLE
Kakoune.cr remaps default normal mode bindings

### ISSUE THREAD

**Issue by gnull** [alexherbo2/kakoune.cr#18]
I installed kakoune.cr with

```kakoune
plug "alexherbo2/kakoune.cr" demand kakoune.cr do %{
    make install
}
```

Now, when I do `<c-f>` in normal mode, it gives me

```
Error: 1:2: 'fzf-files' 2:3: '+' 2:3: 'connect' no such command: 'popup'
```

Instead of going one page forward, like `<c-f>` usually does in normal mode. Looks like kakoune.cr applies by default what is shown in README as an example configuration.

How do I disable this behaviour and load kakoune.cr without changing any of my normal mode bindings?

I tried adding empty config `config %{}` to the `plug` command above, but it didn't change anything.

**Comment by alexherbo2** [comment]
plug.kak sources all `.kak` files, including [`share/kcr/init/example.kak`].

[`share/kcr/init/example.kak`]: https://github.com/alexherbo2/kakoune.cr/blob/master/share/kcr/init/example.kak

**Comment by alexherbo2** [comment]
Closing, as not a kakoune.cr issue.
