### ISSUE TITLE
'Connect' no such command: 'popup'

### ISSUE THREAD

**Issue by aru-hackZ** [alexherbo2/kakoune.cr#2]
I was just following your guide and found really interesting the fzf integration, so I added the keybind mapping `map -docstring "Open files" global normal <c-f> ': + kcr-fzf-files<ret>'`. But the `connect popup` command (which is aliased to `+`) doesn't work:
![image](https://user-images.githubusercontent.com/68018085/109417010-fe7a2980-79c1-11eb-827f-a5ab7581882b.png)
I haven't found any other issues with the rest of `connect` commands.

**Comment by aru-hackZ** [comment]
Im closing the issue, i just found this 😅 :
```kak
hook global ModuleLoaded x11 %{
    alias global popup x11-terminal
}
```

**Comment by alexherbo2** [comment]
For reference: https://github.com/mawww/kakoune/issues/3878
