### ISSUE TITLE
Move auto-pairs.kak into its own repository

### ISSUE THREAD

**Issue by Anomalocaridid** [alexherbo2/kakoune.cr#21]
It seems to work fine without kakoune.cr installed, so I do not understand why it has to be bundled with kakoune.cr. Especially since not everyone who would want auto pairing would necessarily want kakoune.cr and vice versa. In addition, I personally do not have a need for kakoune.cr and would appreciate not having to install it and its dependencies just for the auto-pairs.kak plugin.

**Comment by xnuk** [comment]
I don't know why the author has deleted their repos instead of archiving them, but maybe you want to check this fork: https://github.com/dead10ck/auto-pairs.kak/tree/remove-kcr

**Comment by Anomalocaridid** [comment]
@xnuk Thanks a lot!

**Comment by xnuk** [comment]
I also uploaded two plugins from my cache that I frequently use:
- https://github.com/xnuk/surround.kak
- https://github.com/xnuk/search-highlighter.kak

**Comment by raiguard** [comment]
I agree on this, having the plugins such as auto-pairs and move-lines in separate repositories was so much nicer. Now kcr is becoming a giant conglomerated piece of unrelated scripts, which goes against the Unix philosophy.

**Comment by MaxCan-Code** [comment]
Here's the plug.kak snippet I use to load surround.kak without installing kcr
https://github.com/MaxCan-Code/MaxCan-Code/blob/8fe1d8f2dfafcce1fe60bdbdffed357ab84b83d9/symlinks/foo/.config/kak/kakrc#L12-L15
it also integrates the fixes in #24

**Comment by alexherbo2** [comment]
Done

**Comment by Anomalocaridid** [comment]
Thank you so much!
