### ISSUE TITLE
Use full name instead of shortcut in the doc

### ISSUE THREAD

**Issue by sucrecacao** [alexherbo2/kakoune.cr#22]
Hi, 

In documentation it is usual to use `$` or `>` character to symbolise the prompt, this help distinguish from the command answer eg:
```
$ curl ipinfo.io/city
London
```
It is infortunate that it is also the character you choose for the alias, because it makes the doc hard to read. In my opinion
```
connect-program dolphin
```
is more clear than 
```
$ dolphin
```

Also, I found it difficult to distinguish between the command entered in kakoune prompt and the ones entered in the terminal prompt. This could be more explicit. either by telling it before the code block:
> in kakoune prompt:
>```
>connect-program dolphin
>```
either by using the exec synthax:
> ```
>:connect-program dolphin<ret>
>```
What do you think? Should I submit a PR?

**Comment by alexherbo2** [comment]
Done
