### ISSUE TITLE
auto-pairs: typing closing pair produces an extra one

### ISSUE THREAD

**Issue by maximbaz** [alexherbo2/kakoune.cr#23]
`kakrc` consists of this one line: `source "/usr/share/kcr/rc/auto-pairs.kak"; enable-auto-pairs`

open kak, press `i()`.

Expected: `()`
Actual: `())`

kcr from https://github.com/alexherbo2/kakoune.cr/commit/4f86083e1b9af896815e320cbc1b67488c5cab4c

**Comment by alexherbo2** [comment]
I cannot reproduce.

**Comment by maximbaz** [comment]
I'll try now kakoune from master. Do I need to do anything special when using auto-pairs with kcr? 

we put `/usr/share/kak/rc/addons/kakoune.cr.kak` so kakoune auto-loads that one, that's why I only source `auto-pairs.kak` by hand.

**Comment by maximbaz** [comment]
OK it works as expected in kakoune from master! Want to try to investigate why it doesn't work in the latest stable release? Or close if you are not interested to support the released version
