### ISSUE TITLE
Please remove scripts unnecessarily placed in rc/ and lib.kak

### ISSUE THREAD

**Issue by JacobTravers** [alexherbo2/kakoune.cr#29]
Lumping plugin scripts into [rc/](https://github.com/alexherbo2/kakoune.cr/tree/master/share/kcr/rc) and [lib.kak](https://github.com/alexherbo2/kakoune.cr/blob/master/share/kcr/rc/lib.kak) is [incohesive ](https://www.wikiwand.com/en/Cohesion_(computer_science)#/Types_of_cohesion) given the [intended use-case ](https://github.com/alexherbo2/kakoune.cr#what-can-i-do) of kakoune.cr. Each of these functions provide conflicts to other plugins which many people would prefer (auto-pair, surround, find, palette, etc) and none of these functions are related to the stated focus of kakoune.cr. Conglomerating unrelated functions into one project is a very poor design choice, especially in the context of a plugin. Most new users will choose not to bother with kakoune.cr after manually installing it (opposed to plug.kak) and finding out that the bloat will conflict with their preferred plugins and break their entire config. 

At the very least the extra functions should be separated into a “library” repo:

* still less repos to maintain for the author
* understood that users copy/clone/source from the library however they see fit
* kakoune.cr stays cohesive and predictable
* kakoune.cr remains interoperable with existing configs and separate plugins
* kakoune.cr is easier to maintain as an end user

**Comment by alexherbo2** [comment]
Done
