### ISSUE TITLE
AUR package is broken

### ISSUE THREAD

**Issue by JacobTravers** [alexherbo2/kakoune.cr#35]
trying to install the AUR package results in this error:
```
asciidoctor: FAILED: input file share/kcr/pages/*.asciidoc is missing
```

**Comment by Ordoviz** [comment]
Fixed. Note that issues with the AUR package should be reported to https://aur.archlinux.org/packages/kakoune.cr-git/

**Comment by JacobTravers** [comment]
@Ordoviz my apologies, thank you for the quick response nonetheless
