### ISSUE TITLE
Anyway to make auto-focus optionnable/configurable ?

### ISSUE THREAD

**Issue by stacyharper** [alexherbo2/kakoune.cr#36]
I was adjusted to opening multiple files in a row to browse and preview them. With kcr I now lost the control over this behavior cause the focus command is hardcoded inside the "edit" subcommand.

Is there any plan on making kcr configurable over config file or environment variables ?

**Comment by alexherbo2** [comment]
I’m in favor of dropping it because it introduces a dependency on a user script and windowing system.
