### ISSUE TITLE
Problem with `bat` preview in `kcr-fzf-buffers`

### ISSUE THREAD

**Issue by loewenheim** [alexherbo2/kakoune.cr#4]
`bat` has a problem with file paths containing `~`, at least when they're quoted as in the `kcr-fzf-buffers` script. This results in the problem in the attached screenshot.
<img width="1904" alt="Bildschirmfoto 2021-03-01 um 16 20 01" src="https://user-images.githubusercontent.com/7622248/109518226-568c5b00-7aaa-11eb-86d4-c206944d9224.png">

**Comment by alexherbo2** [comment]
It could be nice to have a command to get a buffer content.

**Comment by alexherbo2** [comment]
In a connected terminal, you can now do `kcr cat --raw` to get the content of the current buffer, or explicitly pass a buffer list to get their content.
