### ISSUE TITLE
cross-compile friendly home dir

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/kakoune.cr#6]
Story:
I cross-compiled `kcr` to be used on my Raspberry Pi as per [this](https://hugopl.github.io/2019/04/28/Crystal-on-raspberry-pi.html) guide, because I didn't want to install crystal sdk to Raspberry Pi in first place. So cross-compiling went smooth on my mac laptop. But then I discovered that following commands were failing.

 - `kcr init kakoune`
 - `kcr install commands`
 - `kcr install desktop`

I turns out that paths to be used with those commands are hardcoded during compilation. As binary was cross-compiled on mac it used path like `/Users/myname/plugin_path` whereas on linux correct path was `/home/myname/plugin_path`.

Following is a quick patch I've applied to fix the problem, however there is still a bit of hardcoding which corresponds to `plugin_path` of `$HOME/plugin_path`. I believe it could be inferred or otherwise declared.
```
From 6395ffa3b2384542f9af91891d817f65bcef3bdf Mon Sep 17 00:00:00 2001
From: Vladimir Bauer <vbauerster@gmail.com>
Date: Wed, 3 Mar 2021 01:51:57 +0500
Subject: [PATCH 1/2] use HOME for innstall commands

---
 src/cli.cr | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/cli.cr b/src/cli.cr
index 5e8616b..22f51b0 100644
--- a/src/cli.cr
+++ b/src/cli.cr
@@ -375,7 +375,7 @@ module Kakoune::CLI
   end
 
   def install_commands
-    command_paths = Dir[Path[__DIR__, "commands", "*", "kcr-*"]]
+    command_paths = Dir[Path[ENV["HOME"], ".config/kak/plugins/github.com/alexherbo2/kakoune.cr/src", "commands", "*", "kcr-*"]]
     bin_path = Path["~/.local/bin"].expand(home: true)
 
     { command_paths, bin_path.to_s }.tap do |sources, destination|
@@ -400,7 +400,7 @@ module Kakoune::CLI
     end
 
     # Install the desktop application
-    kakoune_desktop_path = Path[__DIR__, "../share/applications/kakoune.desktop"]
+    kakoune_desktop_path = Path[ENV["HOME"], ".config/kak/plugins/github.com/alexherbo2/kakoune.cr/src", "../share/applications/kakoune.desktop"]
     kakoune_desktop_install_path = Path[ENV["XDG_DATA_HOME"], "applications/kakoune.desktop"]
 
     { kakoune_desktop_path.to_s, kakoune_desktop_install_path.to_s, kakoune_desktop_install_path.dirname }.tap do |source, destination, directory|
@@ -411,7 +411,7 @@ module Kakoune::CLI
   end
 
   def read(part)
-    File.read(Path[__DIR__] / part)
+    File.read(Path[ENV["HOME"], ".config/kak/plugins/github.com/alexherbo2/kakoune.cr/src"] / part)
   end
 
   def print_json(data)
-- 
2.30.1

```

**Comment by vbauerster** [comment]
Another solution to this, would be to drop those commands from the binary altogether and delegate their functionality to `make install`. Rationale is that `install` commands need to be run once. Dropping `init` command will sacrifice usage of:
```
evaluate-commands %sh{
  kcr init kakoune
}
```
however [init script](https://github.com/alexherbo2/kakoune.cr/blob/master/src/init/kakoune.kak) could be loaded manually with `source` command which I personally prefer.

**Comment by alexherbo2** [comment]
I like to have a single binary and commands to install.

[`env.cr`] is loaded by [`cli.cr`].  I suspect `$XDG_DATA_HOME` to be hardcoded as well?

[`cli.cr`]: https://github.com/alexherbo2/kakoune.cr/blob/master/src/cli.cr
[`env.cr`]: https://github.com/alexherbo2/kakoune.cr/blob/master/src/env.cr

[Broot] and [Starship] have similar commands.  It seems the correct approach is to load the files in memory, so we do not have to ship extra files.

[Broot]: https://dystroy.org/broot/
[Starship]: https://starship.rs

That said, I’m not very fond of in memory files, so if we can avoid it, I would rather fix the hardcoded paths.  We could use a path relative to the binary and look in `../share/kcr`.

How do you do for example with Kakoune?, which has a [`kakrc`] and a [runtime directory][`share/kak`].  If you only import the binary you will not have the shipped config.

[`kakrc`]: https://github.com/mawww/kakoune/blob/master/share/kak/kakrc
[`share/kak`]: https://github.com/mawww/kakoune/tree/master/share/kak

For the [Kakoune definitions], you can write them in a file and save a `sh` call.

``` sh
kcr init kakoune > ~/.config/kak/autoload/kcr.kak
```

[Kakoune definitions]: https://github.com/alexherbo2/kakoune.cr/blob/master/src/init/kakoune.kak

**Comment by vbauerster** [comment]
That's ok to have a single binary responsible for init and install.

What happened is that `HOME` directory expanded to absolute path during compilation, presumably by [\_\_DIR\_\_](https://github.com/alexherbo2/kakoune.cr/blob/master/src/cli.cr#L378) (I'm not familiar with crystal).

Given absolute plugin path on mac:
```
/Users/user/path_to_kakoune.cr
```
I keep `user/path_to_kakoune.cr` part the same across machines. But linux's home starts with `/home` so that broke the install commands because binary was cross-compiled on mac.

I tried to expand `HOME` at runtime in aforementioned patch, but not sure if it's a proper fix. So if you know better fix please go ahead.


>  I suspect `$XDG_DATA_HOME` to be hardcoded as well?

Not sure, but I didn't have any issue installing kcr with `make install` on mac, despite there is no such env var in mac.

**Comment by alexherbo2** [comment]
Should be fixed now.

**Comment by vbauerster** [comment]
Thank you!
Can confirm cross-compiled on mac binary works as expected on linux.
