### ISSUE TITLE
want to include an autoinstaller in the config-kak?

### ISSUE THREAD

**Issue by skewballfox** [alexherbo2/kakoune.cr#7]
I was going through and updating my kak-config and noticed this as a new dependency. since I mianly needed this for auto-pairs.kak, I wrote an installer to automate the installation if kcr isn't a command (heavily based on the autoinstaller for plug.kak), this doesn't handle the dependencies but I thought you might be interested in including this in the readme for either this project or auto-pairs.kak

```
plug "alexherbo2/auto-pairs.kak" evaluate-commands %sh{
    current_directory=$PWD
    if [ ! -x "$(command -v kcr)" ]; then
        current_directory=$PWD
        mkdir $HOME/.config/kak/build && cd $HOME/.config/build
        git clone -q https://github.com/alexherbo2/kakoune.cr
        cd kakoune.cr && make install
        cd $current_directory
    fi

    kcr init kakoune
} 
```

**Comment by alexherbo2** [comment]
I recommend rather the following structure.

`~/.config/kak/kakrc`

``` kak
evaluate-commands %sh{
  kcr init kakoune
}

plug ... %{
  ...
}
```

As a side note, I’m not interested in including notes for a plugin manager.
