### ISSUE TITLE
do you mind if I fork this to add actions/releases?

### ISSUE THREAD

**Issue by skewballfox** [alexherbo2/kakoune.cr#8]
I wanted to learn more about deployment pipelines and the dev ops toolchain. I saw in [this](https://discuss.kakoune.com/t/kakoune-cr/1605/23) discussion that releases can be generated by github itself though github actions. I was wondering if you would be okay with this. if it works you could just merge it back into the main repository.

**Comment by alexherbo2** [comment]
It could be nice to have them.

Currently, I use the following [`Dockerfile`] and [script][`build-static`] for static builds, and I have no experience either with [GitHub Actions].

[`Dockerfile`]: https://github.com/alexherbo2/kakoune.cr/blob/master/Dockerfile
[`build-static`]: https://github.com/alexherbo2/kakoune.cr/blob/master/scripts/build-static
[GitHub Actions]: https://github.com/features/actions

**Comment by skewballfox** [comment]
sweet, I forked it and added the crystal workflow to play around with, and cloned it. I should have something to within the next few days.

**Comment by alexherbo2** [comment]
Added [`release.yml`] and updated the [Installation] section.

No support for macOS yet.

[Installation]: https://github.com/alexherbo2/kakoune.cr#installation
[`release.yml`]: https://github.com/alexherbo2/kakoune.cr/blob/master/.github/workflows/release.yml

**Comment by skewballfox** [comment]
oh okay. I was a variation of the command from @vbauerster from the forum. I also wasn't using the makefile and using crystal directly though:

```
 - name: create release for mac
        run: crystal build --cross-compile --target "x86_64-apple-darwin20.3.0" --release -o kcr src/cli.cr
     
      - name: create release for rpi64
        run: crystal build --cross-compile --target "aarch64-unknown-linux-gnu" --release -o kcr src/cli.cr
```
I hadn't changed the ouput directory because I wasn't sure where the output was supposed to be stored, you can see the entire thing [here](https://github.com/skewballfox/kakoune.cr/blob/master/.github/workflows/create-releases.yml)

**Comment by skewballfox** [comment]
I was only doing it on push, and only when given a semver tag, because I think on free accounts github limits your monthly run time for actions. I was planning on adding automatic versioning, so you could just push with some way of specifying "I want this push to be built"

**Comment by skewballfox** [comment]
on the macOS build, since after looking at the original post again I noticed it's not currently possible to cross compile for macOS, a possible workaround would be to get someone with a mac system to build it on their local system and publish that. doing so in an automated fashion seems like it would be rather hackish.

**Comment by alexherbo2** [comment]
I’ve seen the use of a [matrix][Using a build matrix] in [Install Crystal].

[Install Crystal]: https://github.com/marketplace/actions/install-crystal
[Using a build matrix]: https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

**Comment by alexherbo2** [comment]
As you wish.  I learn the GitHub Actions as the same time as you. 😆

If you have nice solutions, I will gladly take them.

**Comment by alexherbo2** [comment]
@skewballfox We have Linux and macOS releases now 🥳
