### ISSUE TITLE
kcr edit doesn't play well with kakoune-state-save

### ISSUE THREAD

**Issue by gustavo-hms** [alexherbo2/kakoune.cr#9]
Hi, @alexherbo2 !

If I have the [kakoune-state-save](https://gitlab.com/Screwtapello/kakoune-state-save) plugin installed and open a file in Kakoune, it restores the selections from a previous edit.

It also works if I open the file using `kak -p`:
```
echo "edit somefile" | kak -p #session
```

However, if I do the same using `kcr edit somefile`, selections are not restored.

**Comment by alexherbo2** [comment]
Re @gustavo-hms,

I was living happy with this bug until you mentioned it. XD

I also use [kakoune-state-save], so thank you very much.

[kakoune-state-save]: https://gitlab.com/Screwtapello/kakoune-state-save

**Comment by gustavo-hms** [comment]
Thank you for fixing it, and particularly for being so fast!
